/**
 * Recurring reset schedules (configuration, reviewed in code; synced by `pnpm seed`).
 *
 * Every rule cites where the schedule was researched (docs/research/2026-10-02-*.md).
 * All rules stay UNVERIFIED until a person confirms them against the live game — flip a rule
 * to MANUAL_VERIFIED only after that check (see docs/RUNBOOK.md › "Verifying reset rules").
 */
import type { ResetRuleDefinition } from '../schemas/reset';

const LOSTARK_GUIDE =
  'https://lostark.game.onstove.com/GameGuide/Pages/%EC%B9%B4%EC%A0%9C%EB%A1%9C%EC%8A%A4%20%EC%A0%84%EC%9E%A5%ED%8C%90';
const MAPLE_GUIDE = 'https://maplestory.nexon.com/Guide/N23GameInformation/Articles/';

export const RESET_RULES: readonly ResetRuleDefinition[] = [
  {
    id: 'lostark-daily',
    gameId: 'lostark',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 6,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: LOSTARK_GUIDE,
    notes:
      'Official game guide: "매일 06시 획득 기회 초기화" (researched 2026-10-02). Needs human verification.',
  },
  {
    id: 'lostark-weekly',
    gameId: 'lostark',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 6,
    minute: 0,
    dayOfWeek: 3,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: LOSTARK_GUIDE,
    notes:
      'Official game guides: "매주 수요일 06시" (researched 2026-10-02). Needs human verification.',
  },
  {
    id: 'maplestory-daily',
    gameId: 'maplestory',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: `${MAPLE_GUIDE}425`,
    notes:
      'Official guide G425: "매일 오전 0시 초기화" (researched 2026-10-02). Needs human verification.',
  },
  {
    id: 'maplestory-weekly',
    gameId: 'maplestory',
    name: '주간 보스·콘텐츠 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: 4,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: `${MAPLE_GUIDE}425`,
    notes:
      'Official guide G425: "주간 컨텐츠는 목요일 오전 0시에 초기화"; boss reset inferred (researched 2026-10-02).',
  },
  {
    id: 'maplestory-monthly',
    gameId: 'maplestory',
    name: '월간 보스 초기화',
    frequency: 'MONTHLY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: 1,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: `${MAPLE_GUIDE}459`,
    notes:
      'Guide G459 states once per month; 1st 00:00 is commonly reported, not officially confirmed.',
  },
  {
    id: 'genshin-daily',
    gameId: 'genshin',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://genshin.hoyoverse.com/ko/news',
    notes:
      'Asia server 04:00 (UTC+8) inferred from official event windows ending 03:59 (researched 2026-10-02).',
  },
  {
    id: 'genshin-weekly',
    gameId: 'genshin',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: null,
    notes:
      'Monday 04:00 server time is commonly reported; no official statement found (2026-10-02).',
  },
  {
    id: 'genshin-spiral-abyss',
    gameId: 'genshin',
    name: '나선 비경 갱신',
    frequency: 'CUSTOM_RRULE',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: 'FREQ=MONTHLY;BYMONTHDAY=16',
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://genshin.hoyoverse.com/ko/news',
    notes:
      'Official 7.1 notice: refresh on the 16th of each month. Time of day (04:00) unverified.',
  },
  {
    id: 'genshin-imaginarium-theater',
    gameId: 'genshin',
    name: '현실 속 환상극 시즌 갱신',
    frequency: 'MONTHLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: 1,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://genshin.hoyoverse.com/ko/news',
    notes: 'Official notices: new season on the 1st of each month. Time of day (04:00) unverified.',
  },
  {
    id: 'wuwa-daily',
    gameId: 'wuwa',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://wutheringwaves.kurogames.com/en/main/news/',
    notes:
      'Official 3.7 patch notes: "Sign-in records refresh daily at 04:00 server time" (researched 2026-10-02).',
  },
  {
    id: 'wuwa-weekly',
    gameId: 'wuwa',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: null,
    notes:
      'Monday 04:00 server time is commonly reported; no official statement found (2026-10-02).',
  },
];

export function listResetRuleDefinitions(gameId?: string): ResetRuleDefinition[] {
  return RESET_RULES.filter((rule) => gameId === undefined || rule.gameId === gameId);
}
