/**
 * Recurring reset schedules (configuration, reviewed in code; synced by `pnpm seed`).
 *
 * Every rule cites where the schedule was researched (docs/research/2026-10-02-*.md).
 * All rules stay UNVERIFIED until a person confirms them against the live game — flip a rule
 * to MANUAL_VERIFIED only after that check (see docs/RUNBOOK.md › "Verifying reset rules").
 */
import type { ResetRuleDefinition } from '../schemas/reset';

const LOSTARK_GUIDE =
  'https://lostark.game.onstove.com/GameGuide/Pages/%EC%B9%B4%EC%A0%9C%EB%A1%9C%EC%8A%A4%20%EC%A0%84%EC%9E%A5%ED%8C%90';
const MAPLE_GUIDE = 'https://maplestory.nexon.com/Guide/N23GameInformation/Articles/';

export const RESET_RULES: readonly ResetRuleDefinition[] = [
  {
    id: 'lostark-daily',
    gameId: 'lostark',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 6,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: LOSTARK_GUIDE,
    notes:
      'Official game guide: "매일 06시 획득 기회 초기화" (researched 2026-10-02). Needs human verification.',
  },
  {
    id: 'lostark-weekly',
    gameId: 'lostark',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 6,
    minute: 0,
    dayOfWeek: 3,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: LOSTARK_GUIDE,
    notes:
      'Official game guides: "매주 수요일 06시" (researched 2026-10-02). Needs human verification.',
  },
  {
    id: 'maplestory-daily',
    gameId: 'maplestory',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: `${MAPLE_GUIDE}425`,
    notes:
      'Official guide G425: "매일 오전 0시 초기화" (researched 2026-10-02). Needs human verification.',
  },
  {
    id: 'maplestory-weekly',
    gameId: 'maplestory',
    name: '주간 보스·콘텐츠 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: 4,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: `${MAPLE_GUIDE}425`,
    notes:
      'Official guide G425: "주간 컨텐츠는 목요일 오전 0시에 초기화"; boss reset inferred (researched 2026-10-02).',
  },
  {
    id: 'maplestory-monthly',
    gameId: 'maplestory',
    name: '월간 보스 초기화',
    frequency: 'MONTHLY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: 1,
    rrule: null,
    anchor: null,
    region: 'kr',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: `${MAPLE_GUIDE}459`,
    notes:
      'Guide G459 states once per month; 1st 00:00 is commonly reported, not officially confirmed.',
  },
  {
    id: 'genshin-daily',
    gameId: 'genshin',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://genshin.hoyoverse.com/ko/news',
    notes:
      'Asia server 04:00 (UTC+8) inferred from official event windows ending 03:59 (researched 2026-10-02).',
  },
  {
    id: 'genshin-weekly',
    gameId: 'genshin',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: null,
    notes:
      'Monday 04:00 server time is commonly reported; no official statement found (2026-10-02).',
  },
  {
    id: 'genshin-spiral-abyss',
    gameId: 'genshin',
    name: '나선 비경 갱신',
    frequency: 'CUSTOM_RRULE',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: 'FREQ=MONTHLY;BYMONTHDAY=16',
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://genshin.hoyoverse.com/ko/news',
    notes:
      'Official 7.1 notice: refresh on the 16th of each month. Time of day (04:00) unverified.',
  },
  {
    id: 'genshin-imaginarium-theater',
    gameId: 'genshin',
    name: '현실 속 환상극 시즌 갱신',
    frequency: 'MONTHLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: 1,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://genshin.hoyoverse.com/ko/news',
    notes: 'Official notices: new season on the 1st of each month. Time of day (04:00) unverified.',
  },
  {
    id: 'wuwa-daily',
    gameId: 'wuwa',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://wutheringwaves.kurogames.com/en/main/news/',
    notes:
      'Official 3.7 patch notes: "Sign-in records refresh daily at 04:00 server time" (researched 2026-10-02).',
  },
  {
    id: 'wuwa-weekly',
    gameId: 'wuwa',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: null,
    notes:
      'Monday 04:00 server time is commonly reported; no official statement found (2026-10-02).',
  },
  {
    id: 'zzz-daily',
    gameId: 'zzz',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://zenless.hoyoverse.com/ko-kr/news/166192',
    notes:
      'Official notices reset daily features at 04:00 server time = 05:00 KST (news/166192, 165145); the general daily reset is inferred (researched 2026-10-02).',
  },
  {
    id: 'zzz-weekly',
    gameId: 'zzz',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    region: 'asia',
    isPrimary: true,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://zenless.hoyoverse.com/ko-kr/news/127445',
    notes:
      'Official 1.4 notice: Ridu Weekly refreshes every Monday 04:00 server time = 05:00 KST; the general weekly reset is inferred (researched 2026-10-02).',
  },
  {
    id: 'zzz-shiyu-critical-node',
    gameId: 'zzz',
    name: '시유 방어전 격변 구간 갱신',
    frequency: 'CUSTOM_RRULE',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: 'FREQ=WEEKLY;INTERVAL=2;BYDAY=FR',
    anchor: '2025-01-03T04:00:00+08:00',
    region: 'asia',
    isPrimary: false,
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://zenless.hoyoverse.com/ko-kr/news/127445',
    notes:
      'Official 1.4 notice: Critical Node refreshes every 2 weeks on Friday 04:00 server time, next on 2025-01-03. Phases are cut at version ends, so check the current cycle in game (researched 2026-10-02).',
  },
  {
    id: 'hsr-daily',
    gameId: 'hsr',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'asia',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://www.pockettactics.com/honkai-star-rail/server-time',
    notes:
      'Asia server 04:00 UTC+8 (05:00 KST) daily, Monday weekly; third-party guides (researched 2026-10-08).',
  },
  {
    id: 'hsr-weekly',
    gameId: 'hsr',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'UTC+8',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'asia',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://www.pockettactics.com/honkai-star-rail/server-time',
    notes:
      'Asia server 04:00 UTC+8 (05:00 KST) daily, Monday weekly; third-party guides (researched 2026-10-08).',
  },
  {
    id: 'bluearchive-daily',
    gameId: 'bluearchive',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://gachalist.com/daily-resets',
    notes:
      '04:00 KST daily, Monday 04:00 weekly; third-party reset tracker and community answers (researched 2026-10-08).',
  },
  {
    id: 'bluearchive-weekly',
    gameId: 'bluearchive',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://gachalist.com/daily-resets',
    notes:
      '04:00 KST daily, Monday 04:00 weekly; third-party reset tracker and community answers (researched 2026-10-08).',
  },
  {
    id: 'nikke-daily',
    gameId: 'nikke',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 5,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://namu.wiki/w/%EB%A6%AC%EC%85%8B%20%EC%8B%9C%EA%B0%84',
    notes:
      '05:00 KST daily, Tuesday 05:00 weekly from community and wiki sources only; low confidence (researched 2026-10-08).',
  },
  {
    id: 'nikke-weekly',
    gameId: 'nikke',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 5,
    minute: 0,
    dayOfWeek: 2,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://namu.wiki/w/%EB%A6%AC%EC%85%8B%20%EC%8B%9C%EA%B0%84',
    notes:
      '05:00 KST daily, Tuesday 05:00 weekly from community and wiki sources only; low confidence (researched 2026-10-08).',
  },
  {
    id: 'umamusume-daily',
    gameId: 'umamusume',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 5,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://kakaogames.oqupie.com/portals/1576/articles/34538',
    notes:
      '05:00 KST daily (limited sales end 04:59) from a reposted Kakao notice and the wiki; weekly reset unknown (researched 2026-10-08).',
  },
  {
    id: 'trickcal-daily',
    gameId: 'trickcal',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://trickcal.com/',
    notes:
      '04:00 KST daily, consistent with official update times; weekly reset unknown (researched 2026-10-08).',
  },
  {
    id: 'arknights-daily',
    gameId: 'arknights',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://x.com/ArknightsKorea/status/2055907954067656929',
    notes:
      '04:00 KST daily inferred from official KR banner times (04:00 ~ 03:59); Monday weekly from global guides, unconfirmed for KR (researched 2026-10-08).',
  },
  {
    id: 'arknights-weekly',
    gameId: 'arknights',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://x.com/ArknightsKorea/status/2055907954067656929',
    notes:
      '04:00 KST daily inferred from official KR banner times (04:00 ~ 03:59); Monday weekly from global guides, unconfirmed for KR (researched 2026-10-08).',
  },
  {
    id: 'limbus-daily',
    gameId: 'limbus',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 6,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://gachalist.com/daily-resets?page=4',
    notes:
      '06:00 KST daily, Thursday 06:00 weekly (Mirror Dungeon); third-party tracker and community (researched 2026-10-08).',
  },
  {
    id: 'limbus-weekly',
    gameId: 'limbus',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 6,
    minute: 0,
    dayOfWeek: 4,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://gachalist.com/daily-resets?page=4',
    notes:
      '06:00 KST daily, Thursday 06:00 weekly (Mirror Dungeon); third-party tracker and community (researched 2026-10-08).',
  },
  {
    id: 'epic7-daily',
    gameId: 'epic7',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 3,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://arca.live/b/epic7/174789486',
    notes:
      '03:00 KST daily for the Korea/Asia/Japan server per a reposted official notice; arena reopens Monday 03:00 (researched 2026-10-08).',
  },
  {
    id: 'epic7-weekly',
    gameId: 'epic7',
    name: '주간 초기화',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 3,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://arca.live/b/epic7/174789486',
    notes:
      '03:00 KST daily for the Korea/Asia/Japan server per a reposted official notice; arena reopens Monday 03:00 (researched 2026-10-08).',
  },
  {
    id: 'fgo-daily',
    gameId: 'fgo',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: false,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://arca.live/b/mfgo/105812954',
    notes:
      '04:00 KST daily login and friend summon; weekly master missions refresh Monday 00:00; community and wiki (researched 2026-10-08).',
  },
  {
    id: 'fgo-weekly',
    gameId: 'fgo',
    name: '주간 마스터 미션 갱신',
    frequency: 'WEEKLY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: 1,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://arca.live/b/mfgo/105812954',
    notes:
      '04:00 KST daily login and friend summon; weekly master missions refresh Monday 00:00; community and wiki (researched 2026-10-08).',
  },
  {
    id: 'gf2-daily',
    gameId: 'gf2',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 5,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://arca.live/b/gilrsfrontline2exili/106199100',
    notes:
      '05:00 KST daily (events end 04:59) from community and wiki only; weekly reset unknown (researched 2026-10-08).',
  },
  {
    id: 'hi3-daily',
    gameId: 'hi3',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 4,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://arca.live/b/hk3rd/32247264',
    notes:
      '04:00 daily from a 2021 community post; server zone assumed KST; weekly reset unknown (researched 2026-10-08).',
  },
  {
    id: 'gfl-daily',
    gameId: 'gfl',
    name: '일일 초기화',
    frequency: 'DAILY',
    timezone: 'Asia/Seoul',
    hour: 0,
    minute: 0,
    dayOfWeek: null,
    dayOfMonth: null,
    rrule: null,
    anchor: null,
    isPrimary: true,
    region: 'kr',
    verification: 'UNVERIFIED',
    isSynthetic: false,
    sourceUrl: 'https://namu.wiki/w/%EB%A6%AC%EC%85%8B%20%EC%8B%9C%EA%B0%84',
    notes:
      'Midnight KST daily for the Korean service per the wiki; unconfirmed officially; weekly reset unknown (researched 2026-10-08).',
  },
];

export function listResetRuleDefinitions(gameId?: string): ResetRuleDefinition[] {
  return RESET_RULES.filter((rule) => gameId === undefined || rule.gameId === gameId);
}
